// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Employee struct {
	UUID      string  `json:"uuid"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
}

type Expense struct {
	UUID        string    `json:"uuid"`
	Description *string   `json:"description"`
	CreatedAt   string    `json:"createdAt"`
	Amount      *float64  `json:"amount"`
	Currency    *string   `json:"currency"`
	Employee    *Employee `json:"employee"`
}

type ExpensesResult struct {
	Count    int        `json:"count"`
	Expenses []*Expense `json:"expenses"`
}
